# Generated by Django 5.1.5 on 2025-01-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_file',
            field=models.FileField(blank=True, null=True, upload_to='notice_files'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images'),
        ),
    ]
