# Generated by Django 5.1.5 on 2025-01-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notice_notice_file_notice_notice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_image',
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notice_images')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.notice')),
            ],
        ),
    ]
