# Generated by Django 5.1.5 on 2025-01-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_notice_notice_image_noticeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Time', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
