# Generated by Django 5.1.5 on 2025-01-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
