# Generated by Django 5.1.5 on 2025-01-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('Administrator_Role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.administrator_role')),
            ],
        ),
    ]
