# Generated by Django 5.1.5 on 2025-01-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_administrator_role_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
