# Generated by Django 5.1.5 on 2025-01-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_administrator_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eduaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship', models.CharField(max_length=100)),
                ('eligibility_criteria', models.CharField(max_length=150)),
                ('application_deadline', models.DateField()),
                ('faculty', models.CharField(max_length=100)),
                ('Tuition_Fee', models.IntegerField()),
                ('Admission_Fee', models.IntegerField()),
                ('Other_Charges', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='administrator',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
