# Generated by Django 5.1.5 on 2025-01-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_eduaction_alter_administrator_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
