# Generated by Django 5.1.5 on 2025-01-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_administrator_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduaction',
            old_name='Other_Charges',
            new_name='Year_Charge',
        ),
    ]
