# Generated by Django 5.1.5 on 2025-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_eduaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_charges', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('eligibility', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Eduaction',
        ),
    ]
