# Generated by Django 5.1.5 on 2025-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='Administrator_Role',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Administrator_Role',
        ),
    ]
