# Generated by Django 5.1.5 on 2025-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_administrator_administrator_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_file',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='NoticeImage',
        ),
    ]
