# Generated by Django 5.1.5 on 2025-01-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_notice_notice_file_notice_notice_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(blank=True, upload_to='notice_images'),
        ),
    ]
