# Generated by Django 5.1.5 on 2025-01-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_scholarship_uploaded_alter_notice_notice_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
