# Generated by Django 5.1.5 on 2025-01-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_gallery_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
