# Generated by Django 5.1.5 on 2025-01-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_classes_subjects_student_info_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='student_name',
        ),
    ]
