# Generated by Django 5.1.5 on 2025-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_student_info_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='student_first_name',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='student_info',
            name='student_last_name',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
