# Generated by Django 5.1.5 on 2025-01-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_student_info_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sub_subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
