# Generated by Django 5.1.5 on 2025-01-23 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_student_info_std_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(verbose_name='Grade/Class')),
                ('section', models.CharField(max_length=30, verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Subject Name')),
                ('sub_name', models.CharField(blank=True, max_length=30, verbose_name='Sub-Subject Name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.RemoveField(
            model_name='classes',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='students',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='std_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_profile',
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('profile_picture', models.ImageField(blank=True, upload_to='student_profiles/', verbose_name='Profile Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'Student Info',
                'verbose_name_plural': 'Student Infos',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.class', verbose_name='Enrolled Class')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.studentinfo', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(to='home.subject', verbose_name='Subjects'),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Student_info',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'section')},
        ),
    ]
