# Generated by Django 5.1.5 on 2025-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_class_subject_remove_classes_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sub_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_specialized',
            field=models.BooleanField(default=False, verbose_name='Is Specialized Subject?'),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], verbose_name='Grade/Class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Subject Name'),
        ),
    ]
