# Generated by Django 5.1.5 on 2025-01-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.class'),
        ),
    ]
