# Generated by Django 5.1.5 on 2025-01-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_notes_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notes_pdfs'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='student_profiles', verbose_name='Profile Picture'),
        ),
    ]
