# Generated by Django 5.1.5 on 2025-01-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_notes_pdf_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
