# Generated by Django 5.1.5 on 2025-01-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classs',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classs',
            field=models.ManyToManyField(to='home.class'),
        ),
    ]
