# Generated by Django 5.1.5 on 2025-01-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_teacher_classs_teacher_classs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
