# Generated by Django 5.1.5 on 2025-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_teacher_subject_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254, verbose_name='Email Address'),
        ),
    ]
