# Generated by Django 5.1.5 on 2025-02-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_studentinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(blank=True, upload_to='book_image')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='home.class')),
                ('book_Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subject', to='home.subject')),
            ],
        ),
    ]
