# Generated by Django 5.1.5 on 2025-02-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'book'},
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
        ),
    ]
