# Generated by Django 5.1.5 on 2025-02-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_books_options_books_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(max_length=30, verbose_name='Section: '),
        ),
    ]
