# Generated by Django 5.1.5 on 2025-02-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(max_length=30, verbose_name='Section'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'section')},
        ),
    ]
