# Generated by Django 5.1.5 on 2025-02-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_class_section_alter_class_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_roll_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
