# Generated by Django 5.1.5 on 2025-02-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_studentinfo_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_roll_number',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Roll Number'),
        ),
    ]
