# Generated by Django 5.1.5 on 2025-02-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_studentinfo_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.CharField(default='Student@gmail.com', max_length=50, verbose_name='Email'),
        ),
    ]
