# Generated by Django 5.1.5 on 2025-02-05 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_rename_teacher_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
