# Generated by Django 5.1.5 on 2025-02-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_notes_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Student ID'),
        ),
    ]
