# Generated by Django 5.1.5 on 2025-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_studentinfo_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Null', max_length=1, verbose_name='Gender'),
        ),
    ]
