# Generated by Django 5.1.5 on 2025-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_studentinfo_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Null', max_length=7, verbose_name='Gender'),
        ),
    ]
