# Generated by Django 5.1.5 on 2025-02-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alter_studentinfo_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='Teacher@gmail.com', max_length=254, verbose_name='Email Address'),
        ),
        migrations.CreateModel(
            name='Head_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ManyToManyField(to='home.class')),
                ('Teacher', models.ManyToManyField(to='home.teacher')),
            ],
        ),
    ]
