# Generated by Django 5.1.5 on 2025-02-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_teacher_email_head_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head_teacher',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='head_teacher',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='head_teacher',
            name='Class',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.class'),
        ),
        migrations.AddField(
            model_name='head_teacher',
            name='Teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
