# Generated by Django 5.1.5 on 2025-02-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_remove_head_teacher_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_teacher',
            name='Class',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.class'),
        ),
        migrations.AlterField(
            model_name='head_teacher',
            name='Teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
