# Generated by Django 5.1.5 on 2025-02-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_head_teacher_options_alter_head_teacher_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Head_teacher',
        ),
    ]
