# Generated by Django 5.1.5 on 2025-02-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_delete_head_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.class', verbose_name='Class')),
                ('Teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Class_Teacher',
            },
        ),
    ]
