# Generated by Django 5.1.5 on 2025-02-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_head_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
