# Generated by Django 5.1.5 on 2025-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alter_studentinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, upload_to='message_image'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_pdf',
            field=models.FileField(blank=True, upload_to='message_pdf'),
        ),
    ]
