# Generated by Django 5.1.7 on 2025-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_teacher_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_guardian',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Guardian Name'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_guardian_contact',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Guardian Contact'),
        ),
    ]
