# Generated by Django 5.1.7 on 2025-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_studentinfo_student_guardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
