# Generated by Django 5.1.7 on 2025-03-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='fcm_token',
        ),
    ]
