# Generated by Django 5.1.7 on 2025-03-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_teacher_experrienec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='experrienec',
            new_name='experience',
        ),
    ]
